### ISSUE TITLE
Package wrongly shown with "uncommited changes" status

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#664] opened 2018-04-20 22:26 UTC
**OS**

Windows 10

**Pharo**

60540

**Iceberg**

0.7.2

**Problem**

I tried to install ChartJs project via this script:

```Smalltalk
Metacello new
	githubUser: 'DuneSt' project: 'ChartJs' commitish: 'development' path: 'src';
	baseline: 'ChartJs';
	onUpgrade: [ :ex | ex useIncoming ];
	load
```

At the time of the issue "development" is at commit "129574b". (I'll probably do new commits soon that will change the packages structure)

After installing it, if I open Iceberg I see the project as "dirty" and if I open it I see the package "ChartJs" with the "Uncommited changes" status. But there is no change and if I try to commit it show nothing.

**Comment by guillep** [comment] 2018-04-22 10:38
Thanks! I'll try that! Having the exact commits indeed helps in reproducing the bug

**Comment by jecisc** [comment] 2018-05-02 09:05
In Pharo 6.1 I can still reproduce it.

Since I am working on the project on example I'll give another example.

I can reproduce it with this script:

```Smalltalk
Metacello new
	githubUser: 'jecisc' project: 'FileLibraryHelper' commitish: 'master' path: 'src';
	baseline: 'FileLibraryHelper';
	onUpgrade: [ :e | e useIncoming ];
	load
```

The project FileLibraryHelper ends dirty.

**Comment by guillep** [comment] 2018-05-02 12:54
I could reproduce it in Pharo7! Package FileLibraryHelper is dirty :)

Testing testing testing

**Comment by guillep** [comment] 2018-05-02 13:10
Nailed it. Apparently there is a bug in RPackageSet. RPackageSet maintains a cache of definitions and rpackages while loading things with monticello. For some reason, that cache contains an RPackageSet instance of the `FileLirbraryHelper` package, but it has inside a (wrongly) cached collection of methods and classes that is empty!

If I do this on Iceberg when the loading has be announced, the problem is fixed.
```RPackageSet cacheActive: false.```

Now I have to build a test to reproduce it

**Comment by guillep** [comment] 2018-05-02 13:57
Another issue was related to the rpackage set cache: the packages marked as dirty were the ones that were called the same as the repository because of a typo.

All this is tested now and working in 859c5e3

**Closed by guillep** 2018-05-02 13:57 UTC
Labels: Model, bug, important

**Comment by jecisc** [comment] 2018-05-16 23:46
@guillep I got it again... Loading dev branch of MaterialDesignLite in Pharo 6.1 with Iceberg dev-0.7 (0f1b326ebc23237e773e9b8a7de98b3e3024464a)

![image](https://user-images.githubusercontent.com/9519971/40149473-282a0730-5974-11e8-8753-708fdcffdbc2.png)
