### ISSUE TITLE
Pull request cancel 

### ISSUE THREAD

**Issue by sbragagnolo** [pharo-vcs/iceberg#928] opened 2018-07-23 08:40 UTC
When you try to do a pull request from the Iceberg UI, a dialog propts the user for credentials. 

If the user press on cancel without filling up the credential form, it explode (probably there is an if missing)

**Comment by guillep** [comment] 2018-07-31 15:10
I cannot reproduce it in latest iceberg. I'll close it for now.
If you see it again after the next release, please, reopen it.

**Closed by guillep** 2018-07-31 15:10 UTC
Labels: in progress
