### ISSUE TITLE
Handle multiple states of a package: new-saved-deleted

### ISSUE THREAD

**Issue by npasserini** [pharo-vcs/iceberg#113] opened 2016-08-11 09:24 UTC
And review 
1) Iceberg.package/IceSavedPackage.class/instance/nextVersionName.st
Handles an Error as a hacky initial support for new packages.

2) Iceberg.package/IceRepository.class/instance/getOrCreatePackageNamed..st
Adds a new package to the repository if it does not exist, we should mark it as new (and maybe rethink if it is the best place to do this).

**Comment by npasserini** [comment] 2016-08-11 09:25
See sample image from @guillep https://mail.google.com/mail/u/0/#inbox/15674b78bc743a0a

**Comment by guillep** [comment] 2018-04-06 22:30
Duplicate of #82
Right now we identify a new package as a package with changes, a saved package as a package with no changes.

We are missing deleted packages.

**Closed by guillep** 2018-04-06 22:30 UTC
Labels: important
