### ISSUE TITLE
Package wrongly shown with "uncommited changes" status 2

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#804] opened 2018-05-17 13:47 UTC
**OS**

Windows 10

**Pharo**

60540

**Iceberg**

dev-0.7 (0f1b326ebc23237e773e9b8a7de98b3e3024464a)

**Problem**

I tried to install Material Design Lite project via this script:

```Smalltalk
Metacello new
	githubUser: 'DuneSt' project: 'MaterialDesignLite' commitish: 'development' path: 'src';
	baseline: 'MaterialDesignLite';
	load
```

After installing it, if I open Iceberg I see the project as "dirty" and if I open it I see a package with the "Uncommited changes" status. But there is no change and if I try to commit it show nothing. 

![image](https://user-images.githubusercontent.com/9519971/40149473-282a0730-5974-11e8-8753-708fdcffdbc2.png)

**Comment by jecisc** [comment] 2018-05-17 13:48
Same issue as https://github.com/pharo-vcs/iceberg/issues/664 but with a different cause

**Comment by guillep** [comment] 2018-05-18 16:44
I could not reproduce it in latest iceberg. I'll try again, maybe it has something to do with the order of loading the packages?

**Comment by guillep** [comment] 2018-05-18 20:14
Ok, so definitely this does not happen in Pharo7. I've tried with the version of iceberg that comes there and the development version. I could reproduce it in Pharo 6 however.

**Comment by guillep** [comment] 2018-05-18 20:55
Well, I took a deep look at it. It does not seem Iceberg's fault but something related to traits/class builder (which actually changed in Pharo 7)... More in detail:

- The package `Material-Design-Lite-Extensions` is marked as dirty when `Material-Design-Lite-Demo` is loaded
- Apparently, `Extensions` is loaded before Demo, so the class `MDLExampleComponentWithRightPanel` contains at first a method  `defaultToolbar` that is `as yet unclassified`
- First the class builder creates the class, then it sets the `TRightTabsPanelBrowser` to it. When the trait is set, the method `defaultToolbar` gets recategorized and Iceberg receives an announcement (and thus marks the package as dirty)

Why it was created first as `as yet unclassified`? I'm not sure... But maybe the complexity to fix this (in Pharo itself) is not worth it...

I think I'll close it for now, as the issue contains at least a good diagnostic and the problem. Please, reopen if you find a solution.

**Closed by guillep** 2018-05-18 20:55 UTC
Labels: Metacello Integration, Pharo6-backport, bug
