### ISSUE TITLE
create a new file kind of loops

### ISSUE THREAD

**Issue by Ducasse** [pharo-vcs/iceberg#812] opened 2018-05-21 09:28 UTC
I thought that it would create it when I press create a new file but it does not

![screen shot 2018-05-21 at 11 24 45](https://user-images.githubusercontent.com/432549/40300592-fbb68038-5ce9-11e8-8bda-d0601ee245ad.png)

**Comment by Ducasse** [comment] 2018-05-21 09:33
I tried to fix it by doing a command-line pull and after I got 
![screen shot 2018-05-21 at 11 31 43](https://user-images.githubusercontent.com/432549/40300791-8f76afaa-5cea-11e8-908e-8ea908ff5c39.png)


It looks like pillar archetypes changed and now I cannot push my changes. I kept my image to show you.

**Comment by guillep** [comment] 2018-05-22 08:18
That looks like a Pharo issue (at least first issue, the looping).
The second is a well known issue that arrives in certain (complicated but known way to reproduce) situations, so we should fix it but it is lower in the priority list because it impacts few users...

**Comment by guillep** [comment] 2018-05-22 08:49
For the first issue, i've opened

https://pharo.fogbugz.com/f/cases/21938/FileDoesNotExistException-defaultAction-has-some-glitches

The second issue is already open in

https://github.com/pharo-vcs/iceberg/issues/648

I'll close this one as it is duplicated

**Closed by guillep** 2018-05-22 08:49 UTC
