### ISSUE TITLE
Iceberg does not detect change if we update extension methods

### ISSUE THREAD

**Issue by jecisc** [pharo-vcs/iceberg#403] opened 2017-07-13 23:46 UTC
I changed 4 extensions methods but when I want to sync I see no change.

**Comment by jecisc** [comment] 2017-07-13 23:48
And when I commit, the commit is empty.

**Comment by jecisc** [comment] 2017-07-13 23:52
Also, this is weird. IceClassChange has the methods from the *Iceberg-UI protocol in the IceClassChange.class -> instance folder and not in the Iceberg-UI.class -> IceClassChange.extension folder. Is that normal?

**Comment by theseion** [comment] 2017-08-27 07:21
Should be fixed with PR #452 (see issue #450).

**Comment by jecisc** [comment] 2017-08-29 17:29
No. I still don't see extension methods in the sync view.

**Comment by estebanlm** [comment] 2017-08-30 10:45
@jecisc I cannot reproduce, can you give me an example?

**Comment by guillep** [comment] 2018-04-06 22:09
Stale. Please, reopen if this is still an issue with latest version (to be announced)

**Closed by guillep** 2018-04-06 22:09 UTC
Labels: bug
