### ISSUE TITLE
Create branch command do not update UI

### ISSUE THREAD

**Issue by dionisiydk** [pharo-vcs/iceberg#570] opened 2018-02-05 13:02 UTC
Now if you will create branch from Iceberg the table will still show the old one. But in fact it was switched to new one.

**Comment by guillep** [comment] 2018-03-14 09:33
Iceberg 0.7 will entirely rewrite the UI. I'll close this for now. If the issue is still there in the new UI, please re-open.

**Closed by guillep** 2018-03-14 09:33 UTC
